[package]
org = "ballerinax"
name = "mssql"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "sql"
version = "@stdlib.sql.version@"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "@stdlib.crypto.version@"

[[platform.java11.dependency]]
path = "../mssql-native/build/libs/mssql-native-@project.version@.jar"
groupId = "org.ballerinalang"
artifactId = "mssql-native"
version = "@project.version@"


[[platform.java11.dependency]]
path = "@project.path@/repo/balo/ballerina/sql/@stdlib.sql.version@/ballerina-sql-java11-0.5.4.balo"
#path = "@project.path@/repo/balo/ballerina/sql/@stdlib.sql.version@/platform/java11/sql-native-@stdlib.sql.native.version@.jar"
groupId = "org.ballerinalang"
artifactId = "ballerina-sql"
version = "@stdlib.sql.native.version@"


[[platform.java11.dependency]]
path = "./lib/mssql-jdbc.jar"
artafactId = "mssql-jdbc"
groupId = "org.mssql"
scope = "testOnly"
version = "8.2.2.jre8"

    