[package]
org = "ballerinax"
name = "mssql"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "sql"
version = "@stdlib.sql.version@"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "@stdlib.crypto.version@"



    